import { cookies } from 'next/headers'
import React from 'react'
import { ToastContainer } from 'react-toastify'

import { ApolloWrapper, DefaultLayout, Lockscreen } from '@/layouts'

import '@assets/styles/app.scss'
import '@assets/styles/globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Next',
  description: 'Generated by create next app'
}

type Props = {
  children: React.ReactNode
}

export default function RootLayout({ children }: Readonly<Props>) {
  const lockScreen = cookies().get('screen:state')?.value === 'true'
  return (
    <html lang='en' suppressHydrationWarning>
      <body className='font-sans'>
        {lockScreen ? (
          <Lockscreen />
        ) : (
          <ApolloWrapper>
            <DefaultLayout>{children}</DefaultLayout>
          </ApolloWrapper>
        )}
        <ToastContainer position='top-center' autoClose={1000} hideProgressBar={false} draggable={false} />
      </body>
    </html>
  )
}
