import React from 'react'

import { ApolloWrapper } from '@layouts/ApolloWrapper'
import DefaultLayout from '@layouts/default'

import type { Metadata } from 'next'
import '@assets/styles/app.scss'
import '@assets/styles/radix-ui.css'

export const metadata: Metadata = {
  title: 'Next',
  description: 'Generated by create next app'
}

type Props = {
  children: React.ReactNode
}

export default function RootLayout({ children }: Readonly<Props>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body>
        <ApolloWrapper>
          <DefaultLayout>{children}</DefaultLayout>
        </ApolloWrapper>
      </body>
    </html>
  )
}
